<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup Label="Third party">
    <!--<PackageVersion Include="FolkerKinzel.VCards" Version="8.2.0" />-->
  </ItemGroup>
  <ItemGroup Label="System">
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>
  <ItemGroup Label="Windows">
    <PackageVersion Include="System.Windows.Extensions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup Label="Extensions">
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup Label="Testing">
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.10.0" />
  </ItemGroup>
  <ItemGroup Label="Code analysis">
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
  </ItemGroup>
</Project>