<Project>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ComVisible>false</ComVisible>
    <Authors>Jim Dale</Authors>
    <Version>1.0.0.0</Version>
    <NeutralLanguage>en-GB</NeutralLanguage>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <!-- Enable .NET analyzers -->
  <PropertyGroup Condition="'$(IsTestProject)' != 'true'">
    <Deterministic>true</Deterministic>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
  </PropertyGroup>

  <!-- Common settings and package references added to every SDK-style project in the repo (excluded for test projects) -->
  <ItemGroup Condition="'$(IsTestProject)' != 'true'">
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />

    <COMReference Include="Microsoft.Office.Interop.Outlook">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>6</VersionMinor>
      <VersionMajor>9</VersionMajor>
      <Guid>00062fff-0000-0000-c000-000000000046</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>

    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
