namespace Lookout;

using Microsoft.Extensions.Logging;
using Outlook = Microsoft.Office.Interop.Outlook;

/// <summary>
/// Provides strongly-typed logging definitions for the classes in this library.
/// </summary>
/// <remarks>
/// This class contains partial methods generated by the <see cref="LoggerMessageAttribute"/>
/// to produce high-performance structured log messages for this library.
/// </remarks>
internal static partial class Log
{
    [LoggerMessage(Level = LogLevel.Information, Message = "ExportAttachments/Output folder='{OutputFolder}'/Max recurse levels={MaxRecurseLevels}/What if={WhatIf}")]
    public static partial void ExportAttachments(this ILogger logger, DirectoryInfo outputFolder, int maxRecurseLevels, bool whatIf);

    [LoggerMessage(Level = LogLevel.Information, Message = "Store/Name='{DisplayName}'/Path='{FilePath}'/Id='{StoreID}'/Type={ExchangeStoreType}")]
    public static partial void ProcessingStore(this ILogger logger, string? displayName, string filePath, string storeId, Outlook.OlExchangeStoreType exchangeStoreType);

    [LoggerMessage(Level = LogLevel.Information, Message = "Folder/Name='{FolderName}'/Full path='{FullFolderPath}'/Level={RecurseLevel}")]
    public static partial void ProcessingFolder(this ILogger logger, string folderName, string fullFolderPath, int recurseLevel);

    [LoggerMessage(Level = LogLevel.Information, Message = "SavingAttachment/Source='{SourceFileName}'/Destination='{DestFilePath}'")]
    public static partial void SavingAttachment(this ILogger logger, string SourceFileName, string destFilePath);

    [LoggerMessage(Level = LogLevel.Information, Message = "Mail/Subject='{Subject}'/Attachments={AttachmentsCount}")]
    public static partial void MailAttachmentSummary(this ILogger logger, string subject, int attachmentsCount);

    [LoggerMessage(Level = LogLevel.Information, Message = "Meeting/Subject='{Subject}'/Attachments={AttachmentsCount}")]
    public static partial void MeetingAttachmentSummary(this ILogger logger, string subject, int attachmentsCount);

    [LoggerMessage(Level = LogLevel.Information, Message = "Attachment/Display name='{DisplayName}'/Type={AttachmentType}/Size={Size}")]
    public static partial void ProcessingAttachment(this ILogger logger, string displayName, Outlook.OlAttachmentType attachmentType, int size);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Maximum folder recursion level has been reached.")]
    public static partial void MaxRecusionLevelReached(this ILogger logger);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Attachment/Unsupported attachment type ({AttachmentType})")]
    public static partial void UnsupportedAttachmentType(this ILogger logger, Outlook.OlAttachmentType attachmentType);

    [LoggerMessage(Level = LogLevel.Error, Message = "Failed to process Outlook shared item ({DisplayName})")]
    public static partial void ProcessingSharedItemFailed(this ILogger logger, Exception exception, string displayName);

    [LoggerMessage(Level = LogLevel.Error, Message = "Failed to export Outlook attachments.")]
    public static partial void ExportAttachmentsFailed(this ILogger logger, Exception exception);

    [LoggerMessage(Level = LogLevel.Information, Message = "ListStores")]
    public static partial void ListStores(this ILogger logger);

    [LoggerMessage(Level = LogLevel.Information, Message = "ListContacts/Max recurse levels={MaxRecurseLevels}")]
    public static partial void ListContacts(this ILogger logger, int maxRecurseLevels);

    [LoggerMessage(Level = LogLevel.Error, Message = "Failed to list Outlook stores.")]
    public static partial void ListStoresFailed(this ILogger logger, Exception exception);

    [LoggerMessage(Level = LogLevel.Error, Message = "Failed to list Outlook contacts.")]
    public static partial void ListContactsFailed(this ILogger logger, Exception exception);
}
