// <auto-generated />
namespace OutlookServices;

#nullable enable

using System;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Office.Interop.Outlook;

/// <summary>
/// Provides a name-based accessor for retrieving property values from a _ContactItem instance.
/// </summary>
public static partial class ContactItemPropertyAccessor
{
    extension(_ContactItem item)
    {
        /// <summary>
        /// Gets the values for the specified property names from the underlying item.
        /// </summary>
        /// <remarks>Values may be null. If propertyNames contains duplicates, the last occurrence
        /// determines the stored value. The method uses TryGetPropertyValue to determine presence of each
        /// property.</remarks>
        /// <param name="propertyNames">An array of property names to retrieve; only names present on the item are included in the result.</param>
        /// <returns>A read-only dictionary mapping each found property name to its value. Names not present on the item are
        /// omitted; returns an empty dictionary if no names are provided or none are found.</returns>
        public IReadOnlyDictionary<string, object?> GetPropertyValues(string[] propertyNames)
        {
            if (propertyNames.Length == 0)
            {
                return ImmutableDictionary<string, object?>.Empty;
            }

            Dictionary<string, object?> results = new();
            foreach (string propertyName in propertyNames)
            {
                if (item.TryGetPropertyValue(propertyName, out object? value))
                {
                    results[propertyName] = value;
                }
            }

            return results;
        }

        /// <summary>
        /// Attempts to get the value associated with the specified key.
        /// </summary>
        /// <param name="key">The name of the property to retrieve.</param>
        /// <param name="value">When the method returns, contains the value associated with the specified key if found; otherwise, <see langword="null"/>.</param>
        /// <returns>true if the key was found; otherwise, false.</returns>
        public bool TryGetPropertyValue(string key, [MaybeNullWhen(false)] out object? value)
        {
            switch (key)
            {
                case "Application":
                    value = item.Application;
                    return true;
                case "Class":
                    value = item.Class;
                    return true;
                case "Session":
                    value = item.Session;
                    return true;
                case "Parent":
                    value = item.Parent;
                    return true;
                case "Actions":
                    value = item.Actions;
                    return true;
                case "Attachments":
                    value = item.Attachments;
                    return true;
                case "BillingInformation":
                    value = item.BillingInformation;
                    return true;
                case "Body":
                    value = item.Body;
                    return true;
                case "Categories":
                    value = item.Categories;
                    return true;
                case "Companies":
                    value = item.Companies;
                    return true;
                case "ConversationIndex":
                    value = item.ConversationIndex;
                    return true;
                case "ConversationTopic":
                    value = item.ConversationTopic;
                    return true;
                case "CreationTime":
                    value = item.CreationTime;
                    return true;
                case "EntryID":
                    value = item.EntryID;
                    return true;
                case "FormDescription":
                    value = item.FormDescription;
                    return true;
                case "GetInspector":
                    value = item.GetInspector;
                    return true;
                case "Importance":
                    value = item.Importance;
                    return true;
                case "LastModificationTime":
                    value = item.LastModificationTime;
                    return true;
                case "MAPIOBJECT":
                    value = item.MAPIOBJECT;
                    return true;
                case "MessageClass":
                    value = item.MessageClass;
                    return true;
                case "Mileage":
                    value = item.Mileage;
                    return true;
                case "NoAging":
                    value = item.NoAging;
                    return true;
                case "OutlookInternalVersion":
                    value = item.OutlookInternalVersion;
                    return true;
                case "OutlookVersion":
                    value = item.OutlookVersion;
                    return true;
                case "Saved":
                    value = item.Saved;
                    return true;
                case "Sensitivity":
                    value = item.Sensitivity;
                    return true;
                case "Size":
                    value = item.Size;
                    return true;
                case "Subject":
                    value = item.Subject;
                    return true;
                case "UnRead":
                    value = item.UnRead;
                    return true;
                case "UserProperties":
                    value = item.UserProperties;
                    return true;
                case "Account":
                    value = item.Account;
                    return true;
                case "Anniversary":
                    value = item.Anniversary;
                    return true;
                case "AssistantName":
                    value = item.AssistantName;
                    return true;
                case "AssistantTelephoneNumber":
                    value = item.AssistantTelephoneNumber;
                    return true;
                case "Birthday":
                    value = item.Birthday;
                    return true;
                case "Business2TelephoneNumber":
                    value = item.Business2TelephoneNumber;
                    return true;
                case "BusinessAddress":
                    value = item.BusinessAddress;
                    return true;
                case "BusinessAddressCity":
                    value = item.BusinessAddressCity;
                    return true;
                case "BusinessAddressCountry":
                    value = item.BusinessAddressCountry;
                    return true;
                case "BusinessAddressPostalCode":
                    value = item.BusinessAddressPostalCode;
                    return true;
                case "BusinessAddressPostOfficeBox":
                    value = item.BusinessAddressPostOfficeBox;
                    return true;
                case "BusinessAddressState":
                    value = item.BusinessAddressState;
                    return true;
                case "BusinessAddressStreet":
                    value = item.BusinessAddressStreet;
                    return true;
                case "BusinessFaxNumber":
                    value = item.BusinessFaxNumber;
                    return true;
                case "BusinessHomePage":
                    value = item.BusinessHomePage;
                    return true;
                case "BusinessTelephoneNumber":
                    value = item.BusinessTelephoneNumber;
                    return true;
                case "CallbackTelephoneNumber":
                    value = item.CallbackTelephoneNumber;
                    return true;
                case "CarTelephoneNumber":
                    value = item.CarTelephoneNumber;
                    return true;
                case "Children":
                    value = item.Children;
                    return true;
                case "CompanyAndFullName":
                    value = item.CompanyAndFullName;
                    return true;
                case "CompanyLastFirstNoSpace":
                    value = item.CompanyLastFirstNoSpace;
                    return true;
                case "CompanyLastFirstSpaceOnly":
                    value = item.CompanyLastFirstSpaceOnly;
                    return true;
                case "CompanyMainTelephoneNumber":
                    value = item.CompanyMainTelephoneNumber;
                    return true;
                case "CompanyName":
                    value = item.CompanyName;
                    return true;
                case "ComputerNetworkName":
                    value = item.ComputerNetworkName;
                    return true;
                case "CustomerID":
                    value = item.CustomerID;
                    return true;
                case "Department":
                    value = item.Department;
                    return true;
                case "Email1Address":
                    value = item.Email1Address;
                    return true;
                case "Email1AddressType":
                    value = item.Email1AddressType;
                    return true;
                case "Email1DisplayName":
                    value = item.Email1DisplayName;
                    return true;
                case "Email1EntryID":
                    value = item.Email1EntryID;
                    return true;
                case "Email2Address":
                    value = item.Email2Address;
                    return true;
                case "Email2AddressType":
                    value = item.Email2AddressType;
                    return true;
                case "Email2DisplayName":
                    value = item.Email2DisplayName;
                    return true;
                case "Email2EntryID":
                    value = item.Email2EntryID;
                    return true;
                case "Email3Address":
                    value = item.Email3Address;
                    return true;
                case "Email3AddressType":
                    value = item.Email3AddressType;
                    return true;
                case "Email3DisplayName":
                    value = item.Email3DisplayName;
                    return true;
                case "Email3EntryID":
                    value = item.Email3EntryID;
                    return true;
                case "FileAs":
                    value = item.FileAs;
                    return true;
                case "FirstName":
                    value = item.FirstName;
                    return true;
                case "FTPSite":
                    value = item.FTPSite;
                    return true;
                case "FullName":
                    value = item.FullName;
                    return true;
                case "FullNameAndCompany":
                    value = item.FullNameAndCompany;
                    return true;
                case "Gender":
                    value = item.Gender;
                    return true;
                case "GovernmentIDNumber":
                    value = item.GovernmentIDNumber;
                    return true;
                case "Hobby":
                    value = item.Hobby;
                    return true;
                case "Home2TelephoneNumber":
                    value = item.Home2TelephoneNumber;
                    return true;
                case "HomeAddress":
                    value = item.HomeAddress;
                    return true;
                case "HomeAddressCity":
                    value = item.HomeAddressCity;
                    return true;
                case "HomeAddressCountry":
                    value = item.HomeAddressCountry;
                    return true;
                case "HomeAddressPostalCode":
                    value = item.HomeAddressPostalCode;
                    return true;
                case "HomeAddressPostOfficeBox":
                    value = item.HomeAddressPostOfficeBox;
                    return true;
                case "HomeAddressState":
                    value = item.HomeAddressState;
                    return true;
                case "HomeAddressStreet":
                    value = item.HomeAddressStreet;
                    return true;
                case "HomeFaxNumber":
                    value = item.HomeFaxNumber;
                    return true;
                case "HomeTelephoneNumber":
                    value = item.HomeTelephoneNumber;
                    return true;
                case "Initials":
                    value = item.Initials;
                    return true;
                case "InternetFreeBusyAddress":
                    value = item.InternetFreeBusyAddress;
                    return true;
                case "ISDNNumber":
                    value = item.ISDNNumber;
                    return true;
                case "JobTitle":
                    value = item.JobTitle;
                    return true;
                case "Journal":
                    value = item.Journal;
                    return true;
                case "Language":
                    value = item.Language;
                    return true;
                case "LastFirstAndSuffix":
                    value = item.LastFirstAndSuffix;
                    return true;
                case "LastFirstNoSpace":
                    value = item.LastFirstNoSpace;
                    return true;
                case "LastFirstNoSpaceCompany":
                    value = item.LastFirstNoSpaceCompany;
                    return true;
                case "LastFirstSpaceOnly":
                    value = item.LastFirstSpaceOnly;
                    return true;
                case "LastFirstSpaceOnlyCompany":
                    value = item.LastFirstSpaceOnlyCompany;
                    return true;
                case "LastName":
                    value = item.LastName;
                    return true;
                case "LastNameAndFirstName":
                    value = item.LastNameAndFirstName;
                    return true;
                case "MailingAddress":
                    value = item.MailingAddress;
                    return true;
                case "MailingAddressCity":
                    value = item.MailingAddressCity;
                    return true;
                case "MailingAddressCountry":
                    value = item.MailingAddressCountry;
                    return true;
                case "MailingAddressPostalCode":
                    value = item.MailingAddressPostalCode;
                    return true;
                case "MailingAddressPostOfficeBox":
                    value = item.MailingAddressPostOfficeBox;
                    return true;
                case "MailingAddressState":
                    value = item.MailingAddressState;
                    return true;
                case "MailingAddressStreet":
                    value = item.MailingAddressStreet;
                    return true;
                case "ManagerName":
                    value = item.ManagerName;
                    return true;
                case "MiddleName":
                    value = item.MiddleName;
                    return true;
                case "MobileTelephoneNumber":
                    value = item.MobileTelephoneNumber;
                    return true;
                case "NetMeetingAlias":
                    value = item.NetMeetingAlias;
                    return true;
                case "NetMeetingServer":
                    value = item.NetMeetingServer;
                    return true;
                case "NickName":
                    value = item.NickName;
                    return true;
                case "OfficeLocation":
                    value = item.OfficeLocation;
                    return true;
                case "OrganizationalIDNumber":
                    value = item.OrganizationalIDNumber;
                    return true;
                case "OtherAddress":
                    value = item.OtherAddress;
                    return true;
                case "OtherAddressCity":
                    value = item.OtherAddressCity;
                    return true;
                case "OtherAddressCountry":
                    value = item.OtherAddressCountry;
                    return true;
                case "OtherAddressPostalCode":
                    value = item.OtherAddressPostalCode;
                    return true;
                case "OtherAddressPostOfficeBox":
                    value = item.OtherAddressPostOfficeBox;
                    return true;
                case "OtherAddressState":
                    value = item.OtherAddressState;
                    return true;
                case "OtherAddressStreet":
                    value = item.OtherAddressStreet;
                    return true;
                case "OtherFaxNumber":
                    value = item.OtherFaxNumber;
                    return true;
                case "OtherTelephoneNumber":
                    value = item.OtherTelephoneNumber;
                    return true;
                case "PagerNumber":
                    value = item.PagerNumber;
                    return true;
                case "PersonalHomePage":
                    value = item.PersonalHomePage;
                    return true;
                case "PrimaryTelephoneNumber":
                    value = item.PrimaryTelephoneNumber;
                    return true;
                case "Profession":
                    value = item.Profession;
                    return true;
                case "RadioTelephoneNumber":
                    value = item.RadioTelephoneNumber;
                    return true;
                case "ReferredBy":
                    value = item.ReferredBy;
                    return true;
                case "SelectedMailingAddress":
                    value = item.SelectedMailingAddress;
                    return true;
                case "Spouse":
                    value = item.Spouse;
                    return true;
                case "Suffix":
                    value = item.Suffix;
                    return true;
                case "TelexNumber":
                    value = item.TelexNumber;
                    return true;
                case "Title":
                    value = item.Title;
                    return true;
                case "TTYTDDTelephoneNumber":
                    value = item.TTYTDDTelephoneNumber;
                    return true;
                case "User1":
                    value = item.User1;
                    return true;
                case "User2":
                    value = item.User2;
                    return true;
                case "User3":
                    value = item.User3;
                    return true;
                case "User4":
                    value = item.User4;
                    return true;
                case "UserCertificate":
                    value = item.UserCertificate;
                    return true;
                case "WebPage":
                    value = item.WebPage;
                    return true;
                case "YomiCompanyName":
                    value = item.YomiCompanyName;
                    return true;
                case "YomiFirstName":
                    value = item.YomiFirstName;
                    return true;
                case "YomiLastName":
                    value = item.YomiLastName;
                    return true;
                case "Links":
                    value = item.Links;
                    return true;
                case "ItemProperties":
                    value = item.ItemProperties;
                    return true;
                case "LastFirstNoSpaceAndSuffix":
                    value = item.LastFirstNoSpaceAndSuffix;
                    return true;
                case "DownloadState":
                    value = item.DownloadState;
                    return true;
                case "IMAddress":
                    value = item.IMAddress;
                    return true;
                case "MarkForDownload":
                    value = item.MarkForDownload;
                    return true;
                case "IsConflict":
                    value = item.IsConflict;
                    return true;
                case "AutoResolvedWinner":
                    value = item.AutoResolvedWinner;
                    return true;
                case "Conflicts":
                    value = item.Conflicts;
                    return true;
                case "HasPicture":
                    value = item.HasPicture;
                    return true;
                case "PropertyAccessor":
                    value = item.PropertyAccessor;
                    return true;
                case "TaskSubject":
                    value = item.TaskSubject;
                    return true;
                case "TaskDueDate":
                    value = item.TaskDueDate;
                    return true;
                case "TaskStartDate":
                    value = item.TaskStartDate;
                    return true;
                case "TaskCompletedDate":
                    value = item.TaskCompletedDate;
                    return true;
                case "ToDoTaskOrdinal":
                    value = item.ToDoTaskOrdinal;
                    return true;
                case "ReminderOverrideDefault":
                    value = item.ReminderOverrideDefault;
                    return true;
                case "ReminderPlaySound":
                    value = item.ReminderPlaySound;
                    return true;
                case "ReminderSet":
                    value = item.ReminderSet;
                    return true;
                case "ReminderSoundFile":
                    value = item.ReminderSoundFile;
                    return true;
                case "ReminderTime":
                    value = item.ReminderTime;
                    return true;
                case "IsMarkedAsTask":
                    value = item.IsMarkedAsTask;
                    return true;
                case "BusinessCardLayoutXml":
                    value = item.BusinessCardLayoutXml;
                    return true;
                case "BusinessCardType":
                    value = item.BusinessCardType;
                    return true;
                case "ConversationID":
                    value = item.ConversationID;
                    return true;
                case "RTFBody":
                    value = item.RTFBody;
                    return true;
                default:
                    value = default;
                    return false;
            }
        }
    }
}

#nullable restore
